---
mywin1:
 hosts:
  ansiwindows:
   ansible_user: administrator
   ansible_password: dineshSRV@123
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5986
   ansible_winrm_server_cert_validation: ignore

mywin2:
 hosts:
  ansiwindows:
 vars:
   ansible_user: administrator
   ansible_password: dineshSRV@123
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5986
   ansible_winrm_server_cert_validation: ignore
